#
# Author: Daniel Vogel
# Date:	  2/28/2020
# Filename: iscsii-client.pb
#
# Description: 	Install the iscsi-initiator-utils and do a discovery of iscsi disks.
#		Attach some of these to the nodes and enable/start the iscsi service.
#		Add the ACL for the internal cluster nodes.
#		
# 	ACL:	/etc/iscsi/initiatorname.iscsi
#		InitiatorName=iqn.2014-01.asia.datos:datostech
#

---
- name: Install base packages for cluster
  hosts: san  
  become: true
  tasks:
    - name: install samba & iscsi & gfs2
      yum:
        state: present
        name:
        - samba
        - samba-common
        - samba-client
        - cifs-utils
        - nfs-utils
        - ctdb
        - iscsi-initiator-utils
        - lvm2-cluster
        - gfs2-utils
        - pcs
        - dlm
        - fence-agents-all
